
### Status
GET http://127.0.0.1:8000/status


### Get profile
GET http://127.0.0.1:8000/profile/test.pac


### Create/Update profile
POST http://127.0.0.1:8000/profile/test.pac

function FindProxyForURL(url, host) {
    if (shExpMatch(host,"ifconfig.me")) {
        return "SOCKS proxy.local:1080";
    }
    return "DIRECT";
}

### Delete profile
DELETE http://127.0.0.1:8000/profile/test.pac
